### ISSUE TITLE
receive functions do not appear to be interruptible

### ISSUE THREAD

**Issue by mgsloan** [mstksg/ghcjs-websockets#1]
Hi!  Thanks for this library, it's very handy and well documented :)

Anyway, in practice it seems like async exceptions do not play nicely with the receive functions.  If a receive function is interrupted, then it looks like the next websocket response gets swallowed.  This isn't a bug persay, but was counterintuitive to me.  Ideally this would be documented, and perhaps a layer added to help with this (such as the one below)

I could probably put together a minimal repro if need be.

For now, I am using this to get around this:

``` haskell
-- | Wrapper around JavaScript.WebSockets which has safely interruptible
-- sending and receiving of messages.
--
-- Originally attempted with vanilla Chan, but I ran into what I
-- believe to be an erroneous "thread blocked indefinitely in an MVar
-- operation".
--
-- This may be the issue documented here:
-- https://github.com/ghcjs/ghcjs/issues/320
--
-- (I am using a slighty older GHCJS, and don't have time to test HEAD)
module Communication where

import           Control.Concurrent.Async (race)
import           Control.Concurrent.STM (atomically)
import           Control.Concurrent.STM.TChan
import           Control.Monad (forever)
import           Data.Text (Text)
import           Data.Void (absurd)
import qualified JavaScript.WebSockets as WS

data Connection = Connection
  { receiveTChan :: TChan Text
  , sendTChan :: TChan Text
  , connection :: WS.Connection
  }

-- NOTE: if the websocket disconnects, the inner function is killed.
-- This is due to using the unsafe functions in JavaScript.WebSockets
withUrl :: Text -> (Connection -> IO a) -> IO a
withUrl url f = do
    receiveTChan <- newTChanIO
    sendTChan <- newTChanIO
    result <- WS.withUrl url $ \connection ->
      receiveThread connection receiveTChan `race`
      sendThread connection sendTChan `race`
      f Connection {..}
    case result of
      Left (Left x) -> absurd x
      Left (Right x) -> absurd x
      Right x -> return x
  where
    receiveThread conn chan =
      forever $ WS.receiveText_ conn >>= atomically . writeTChan chan
    sendThread conn chan =
      forever $ atomically (readTChan chan) >>= WS.sendText_ conn

receiveText :: Connection -> IO Text
receiveText = atomically . readTChan . receiveTChan

sendText :: Connection -> Text -> IO ()
sendText conn = atomically . writeTChan (sendTChan conn)
```

**Comment by mstksg** [comment]
Hey @mgsloan !  Thanks for this :) I'll look at this and decide what the proper behavior should really be and decide what documentation to add on deviations it and get back to you.

**Comment by mstksg** [comment]
yeah, the behavior now is definitely not ideal or intended.

Hunted down the source of the bug/odd behavior tonight.  Seems like it might take some rewiring of control flow to fix but it shouldn't be too much, I think.  But those are famous last words :)

**Comment by mstksg** [comment]
okay, found a way to make behavior match what is expected; interrupted receivers should not eat up queued messages in their afterlife.  i'm revamping the api/documentation in the develop branch over the next day or two in prep for a hackage push, so it should be merged into head/master within a few days when that happens.

thanks again for the heads up :)

**Comment by mgsloan** [comment]
I've confirmed that this fixes the issue.  Thanks for the rapid fix!

**Comment by mstksg** [comment]
no problem!  gave me the impetus to clean things up for hackage, haha.  also a good push for me to go in and make sure all async exceptions are properly handled/bubbled.
