### ISSUE TITLE
Bad Binary instance

### ISSUE THREAD

**Issue by oliver-batchelor** [mstksg/ghcjs-websockets#5]
The instance  Binary a => WSReceivable is quite problematic.

I've been fighting with WSReceivable, it seems to pick Binary instead of WSReceivable at arbitrary points regardless of the language extensions turned on.

``` haskell
data SocketEvents t a = SocketEvents
  { message      :: Event t a
  , decodeFail   :: Event t SocketMsg 
  }


-- This is ok
unwrapReceivable :: (Reflex t, WSReceivable a) => Event t SocketMsg ->  (Event t SocketMsg, Event t a)
unwrapReceivable e = (decFail, message) where
  (decFail, message) = splitEither . fmap WS.unwrapReceivable $ e


-- This is not
unwrapReceivable :: (Reflex t, WSReceivable a) => Event t SocketMsg ->  SocketEvents t a
unwrapReceivable e = SocketEvents message decFail where
  (decFail, message) = splitEither . fmap WS.unwrapReceivable $ e
```

```
    Could not deduce (Binary a)
      arising from a use of ‘WS.unwrapReceivable’
    from the context (Reflex t, WSReceivable a)
      bound by the type signature for
                 unwrapReceivable :: (Reflex t, WSReceivable a) =>
                                     Event t SocketMsg -> SocketEvents t a
```

**Comment by mstksg** [comment]
Hm yes, the typeclass and its instances are honestly a bit evil.  It was sort of an "it's okay as long as it's used exactly in these use cases" thing, inspired by the serverside websockets library, heh.  They might be slated for removal if it ends up being a big deal.

For now, have you tried using `ScopedTypeVariables` and manually annotating `message`, `decFail` ?  Like:

``` haskell
unwrapReceivable :: forall t a. (Reflex t, WSReceivable a) => Event t SocketMsg -> SocketEvents t a
unwrapReceivable e = SocketEvents message decFail
  where
    decFail :: Event t SocketMsg
    message :: Event t a
    (decFail, message) = splitEither -- ...
```

If nothing works then it just might be that the WSReceivable typeclass abuse isn't really suited for this sort of thing :)

Maybe I could re-do it to use a newtype wrapper around Binary instances, perhaps.  I'm a bit swamped in the present so I'll try looking at it this weekend.  Thanks for bringing this up :)

**Comment by oliver-batchelor** [comment]
Thanks for the reply. I gave it a play with the manual annotation (and variations), couldn't manage to figure out a way to make it work.

I am curious why it only pops up when I put the 'a' in a record, rather than a tuple (where it is happy).

**Comment by oliver-batchelor** [comment]
Even worse, if I make it monomorphic to Text I get this!

src/WebSocket.hs:166:41:
    Could not deduce (Binary Text)
      arising from a use of ‘WS.unwrapReceivable’

**Comment by mstksg** [comment]
I reproduced the problem in a small toy example not involving Reflex and found something that seemed to appease the type checker; can you see if this works?

``` haskell
unwrapReceivable :: forall a t. (Reflex t, WSReceivable a) => Event t SocketMsg ->  SocketEvents t a
unwrapReceivable e = SocketEvents (fst dfm) (snd dfm)    -- or uncurry SocketEvents dfm
  where
    dfm :: (Event t a, Event t SocketMsg)
    dfm = splitEither . fmap WS.unwrapReceivable $ e
```

In any case, I feel like `WSReceivable` is sort of a hack in the end, so coaxing it to do more interesting things than the wrapped usage the library offers miight be a bit of a shaky endeavour as a whole.  But it does seem useful to an extent, and I'd be interested to hear if you can get it to work with this :)

**Comment by oliver-batchelor** [comment]
Seems to work - I wonder why, apparently avoiding the pattern match does the trick.

**Comment by mstksg** [comment]
it's a bit mysterious to me too.  I'll close the issue as resolved for now but I'll look into this and investigate ways to improve the library design or the documentation at least with this in mind. thanks again!
