### ISSUE TITLE
Error compiling src\JavaScript\WebSockets\FFI.hs

### ISSUE THREAD

**Issue by agocorona** [mstksg/ghcjs-websockets#9]
ghcjs --version
The Glorious Glasgow Haskell Compilation System for JavaScript, version 0.2.0 (GHC 7.10.2)

installing the package from hackage produces:

NoGHCJS.hs, dist\build\JavaScript\NoGHCJS.js_o )
[2 of 5] Compiling JavaScript.WebSockets.FFI ( src\JavaScript\WebSockets\FFI.hs, dist\build\JavaScript\WebSockets\FFI.js_o )

src\JavaScript\WebSockets\FFI.hs:28:28:
    Module `GHCJS.Types' does not export`JSArray'

src\JavaScript\WebSockets\FFI.hs:28:47:
    Module `GHCJS.Types' does not export`JSObject'

src\JavaScript\WebSockets\FFI.hs:28:57:
    Module `GHCJS.Types' does not export`JSBool'
cabal: Error: some packages failed to install:
ghcjs-websockets-0.3.0.5 failed during the building phase. The exception was:
ExitFailure 1

**Comment by mstksg** [comment]
Hm, I suspect this has to do with changes to the new GHCJS base.  I'll start looking into it...but I've also heard that GHCJS now supports websockets natively; if this is the case, switching to that might be better while I try to figure out how ghcjs-base is now arranged?

**Comment by agocorona** [comment]
I have been taking with Luite. Yest GHCJS-base does websockets.  

ghcjs-base has his own problem with websockets but that is a different matter. I will close this:

The problem in ghcjs-base now is related with missing JS methods like  h$closeWebsocker not being found. Luite know about it and he is after it, but he is very busy. 

I think that a good support for websockets is critical. I will continue at the problem after Friday.
